

service: myLambdaService

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: hello
          method: get
          cors: true


